"""
DESCRIPTION:

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

  Input: s = "abcd", t = "abcde"
  Output: "e"
  Explanation: 'e' is the letter that was added.

Example 2:

  Input: s = "", t = "y"
  Output: "y"

 
Constraints:

    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.

"""

from collections import Counter
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        
        """
        Summary:
            Método de la clase Solution encargado de retornar el
            carácter adicional diferencial de dos cadenas de texto.
        Args:
            s (str) -- Cadena de texto de base.
            t (str) -- Cadena de texto con un carácter adicional.
        Returns:
            str -- Carácter diferencial entre ambas cadenas de texto.
        """

        chars_counter = Counter(s)
        chars_counter.update(t)

        for key, value in chars_counter.items():
            if (value % 2) != 0:
                return key